export const ON_AUTH_START = 'ON_AUTH_START';
export const ON_AUTH_SUCCESS = 'ON_AUTH_SUCCESS';
export const ON_AUTH_FAIL = 'ON_AUTH_FAIL';

export const ON_LOGOUT_SUCCESS = 'ON_LOGOUT_SUCCESS';
export const ON_LOGOUT_FAIL = 'ON_LOGOUT_FAIL';