export const ON_AUTH_START = 'ON_AUTH_START';
export const ON_AUTH_SUCCESS = 'ON_AUTH_SUCCESS';
export const ON_AUTH_FAIL = 'ON_AUTH_FAIL';

export const ON_AUTH_ERROR_CLOSE = 'ON_AUTH_ERROR_CLOSE';

export const ON_LOGOUT_SUCCESS = 'ON_LOGOUT_SUCCESS';
export const ON_LOGOUT_FAIL = 'ON_LOGOUT_FAIL';

export const ON_PROFILE_LOAD_START = 'ON_PROFILE_LOAD_START';
export const ON_PROFILE_LOAD_SUCCESS = 'ON_PROFILE_LOAD_SUCCESS';
export const ON_PROFILE_LOAD_FAIL = 'ON_PROFILE_LOAD_FAIL';

export const ON_ADD_PROFILE_IMAGE_START = 'ON_ADD_PROFILE_IMAGE_START';
export const ON_ADD_PROFILE_IMAGE_SUCCESS = 'ON_ADD_PROFILE_IMAGE_SUCCESS';
export const ON_ADD_PROFILE_IMAGE_SUCCESS_CLEAR = 'ON_ADD_PROFILE_IMAGE_SUCCESS_CLEAR';
export const ON_ADD_PROFILE_IMAGE_FAIL = 'ON_ADD_PROFILE_IMAGE_FAIL';
export const ON_ADD_PROFILE_IMAGE_ERROR_CLEAR = 'ON_ADD_PROFILE_IMAGE_ERROR_CLEAR';

export const ON_POST_LOAD_START = 'ON_POST_LOAD_START';
export const ON_POST_LOAD_SUCCESS = 'ON_POST_LOAD_SUCCESS';
export const ON_POST_LOAD_FAIL = 'ON_POST_LOAD_FAIL';

export const ON_PAGE_INC = 'ON_PAGE_INC';

export const ON_USER_DATA_UPDATE_START = 'ON_USER_DATA_UPDATE_START';
export const ON_USER_DATA_UPDATE_SUCCESS = 'ON_USER_DATA_UPDATE_SUCCESS';
export const ON_USER_DATA_UPDATE_FAIL = 'ON_USER_DATA_UPDATE_FAIL';
export const ON_USER_DATA_UPDATE_SUCCESS_CLEAR = 'ON_USER_DATA_UPDATE_SUCCESS_CLEAR';
export const ON_USER_DATA_UPDATE_ERROR_CLEAR = 'ON_USER_DATA_UPDATE_ERROR_CLEAR';

export const ON_USER_PASSWORD_UPDATE_START = 'ON_USER_PASSWORD_UPDATE_START'; 
export const ON_USER_PASSWORD_UPDATE_SUCESS = 'ON_USER_PASSWORD_UPDATE_SUCESS'; 
export const ON_USER_PASSWORD_UPDATE_FAIL = 'ON_USER_PASSWORD_UPDATE_FAIL'; 
export const ON_USER_PASSWORD_UPDATE_SUCCESS_CLEAR = 'ON_USER_PASSWORD_UPDATE_SUCCESS_CLEAR'; 
export const ON_USER_PASSWORD_UPDATE_ERROR_CLEAR = 'ON_USER_PASSWORD_UPDATE_ERROR_CLEAR'; 

export const ON_ADD_POST_START = 'ON_ADD_POST_START';
export const ON_ADD_POST_SUCCESS = 'ON_ADD_POST_SUCCESS';
export const ON_ADD_POST_FAIL = 'ON_ADD_POST_FAIL';
export const ON_ADD_POST_SUCCESS_CLEAR = 'ON_ADD_POST_SUCCESS_CLEAR';
export const ON_ADD_POST_ERROR_CLEAR = 'ON_ADD_POST_ERROR_CLEAR';

export const ON_LIKE_SUCCESS = 'ON_LIKE_SUCCESS';
export const ON_LIKE_FAIL = 'ON_LIKE_FAIL';

export const ON_DISLIKE_SUCCESS = 'ON_DISLIKE_SUCCESS';
export const ON_DISLIKE_FAIL = 'ON_DISLIKE_FAIL';

export const ON_DELETE_POST_START = 'ON_DELETE_POST_START';
export const ON_DELETE_POST_SUCCESS = 'ON_DELETE_POST_SUCCESS';
export const ON_DELETE_POST_FAIL = 'ON_DELETE_POST_FAILE';

export const ON_COMMENT_START = 'ON_COMMENT_START';
export const ON_COMMENT_SUCCESS = 'ON_COMMENT_SUCCESS';
export const ON_COMMENT_FAIL = 'ON_COMMENT_FAIL';
export const ON_COMMENT_SUCCESS_CLEAR = "ON_COMMENT_SUCCESS_CLEAR";
export const ON_COMMENT_ERROR_CLEAR = "ON_COMMENT_ERROR_CLEAR";

export const ON_COMMENT_DELETE_START = 'ON_COMMENT_DELETE_START' ;
export const ON_COMMENT_DELETE_SUCCESS = 'ON_COMMENT_DELETE_SUCCESS' ;
export const ON_COMMENT_DELETE_FAIL = 'ON_COMMENT_DELETE_FAIL' ;

export const ON_FRIENDS_LOAD_START = 'ON_FRIENDS_LOAD_START';
export const ON_FRIENDS_LOAD_SUCCESS = 'ON_FRIENDS_LOAD_SUCCESS';
export const ON_FRIENDS_LOAD_FAIL = 'ON_FRIENDS_LOAD_FAIL';

export const ON_PENDING_REQ_LOAD_START = 'ON_PENDING_REQ_LOAD_START';
export const ON_PENDING_REQ_LOAD_SUCCESS = 'ON_PENDING_REQ_LOAD_SUCCESS';
export const ON_PENDING_REQ_LOAD_FAIL = 'ON_PENDING_REQ_LOAD_FAIL';

export const ON_SENT_REQ_LOAD_START = 'ON_SENT_REQ_LOAD_START';
export const ON_SENT_REQ_LOAD_SUCCESS = 'ON_SENT_REQ_LOAD_SUCCESS';
export const ON_SENT_REQ_LOAD_FAIL = 'ON_SENT_REQ_LOAD_FAIL';

export const ON_SEND_FRIEND_REQ_START = 'ON_SEND_FRIEND_REQ_START';
export const ON_SEND_FRIEND_REQ_SUCCESS = 'ON_SEND_FRIEND_REQ_SUCCESS';
export const ON_SEND_FRIEND_REQ_FAIL = 'ON_SEND_FRIEND_REQ_FAIL';

export const ON_FRIEND_REQ_ACCEPT_START = 'ON_FRIEND_REQ_ACCEPT_START';
export const ON_FRIEND_REQ_ACCEPT_SUCCESS = 'ON_FRIEND_REQ_ACCEPT_SUCCESS';
export const ON_FRIEND_REQ_ACCEPT_FAIL = 'ON_FRIEND_REQ_ACCEPT_FAIL';

export const ON_FRIEND_REQ_REJECT_START = 'ON_FRIEND_REQ_REJECT_START';
export const ON_FRIEND_REQ_REJECT_SUCCESS = 'ON_FRIEND_REQ_REJECT_SUCCESS';
export const ON_FRIEND_REQ_REJECT_FAIL = 'ON_FRIEND_REQ_REJECT_FAIL';

export const ON_FRIEND_REMOVE_START = 'ON_FRIEND_REMOVE_START';
export const ON_FRIEND_REMOVE_SUCCESS = 'ON_FRIEND_REMOVE_SUCCESS';
export const ON_FRIEND_REMOVE_FAIL = 'ON_FRIEND_REMOVE_FAIL';